DROP TABLE IF EXISTS REGISTRATIONS;
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
    id BIGSERIAL PRIMARY KEY,
    username TEXT NOT NULL,
    email TEXT NOT NULL,
    password TEXT NOT NULL,
    role TEXT NOT NULL
);

CREATE TABLE REGISTRATIONS (
    id BIGSERIAL PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    county VARCHAR(255) NOT NULL,
    postcode INT NOT NULL,
    phone_number VARCHAR(50) NOT NULL,
    email VARCHAR(255),
    school VARCHAR(255) NOT NULL,
    session_id VARCHAR(255)
);
